// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Source struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Header struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Http struct {
	Host                 string    `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Method               string    `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string    `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Protocol             string    `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Headers              []*Header `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Http) Reset()         { *m = Http{} }
func (m *Http) String() string { return proto.CompactTextString(m) }
func (*Http) ProtoMessage()    {}
func (*Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http.Unmarshal(m, b)
}
func (m *Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http.Marshal(b, m, deterministic)
}
func (m *Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http.Merge(m, src)
}
func (m *Http) XXX_Size() int {
	return xxx_messageInfo_Http.Size(m)
}
func (m *Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Http proto.InternalMessageInfo

func (m *Http) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Http) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Http) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Http) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Http) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

type GraphQLField struct {
	// path to the graphql field from starting with the operation type.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// the type name of parent of the field
	ParentType string `protobuf:"bytes,2,opt,name=parentType,proto3" json:"parentType,omitempty"`
	// the type name of the field
	FieldType string `protobuf:"bytes,3,opt,name=fieldType,proto3" json:"fieldType,omitempty"`
	// json encoded object holding the arguments passed to the field
	Args                 string   `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphQLField) Reset()         { *m = GraphQLField{} }
func (m *GraphQLField) String() string { return proto.CompactTextString(m) }
func (*GraphQLField) ProtoMessage()    {}
func (*GraphQLField) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GraphQLField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQLField.Unmarshal(m, b)
}
func (m *GraphQLField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQLField.Marshal(b, m, deterministic)
}
func (m *GraphQLField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQLField.Merge(m, src)
}
func (m *GraphQLField) XXX_Size() int {
	return xxx_messageInfo_GraphQLField.Size(m)
}
func (m *GraphQLField) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQLField.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQLField proto.InternalMessageInfo

func (m *GraphQLField) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GraphQLField) GetParentType() string {
	if m != nil {
		return m.ParentType
	}
	return ""
}

func (m *GraphQLField) GetFieldType() string {
	if m != nil {
		return m.FieldType
	}
	return ""
}

func (m *GraphQLField) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type GraphQL struct {
	Fields               []*GraphQLField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GraphQL) Reset()         { *m = GraphQL{} }
func (m *GraphQL) String() string { return proto.CompactTextString(m) }
func (*GraphQL) ProtoMessage()    {}
func (*GraphQL) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GraphQL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQL.Unmarshal(m, b)
}
func (m *GraphQL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQL.Marshal(b, m, deterministic)
}
func (m *GraphQL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQL.Merge(m, src)
}
func (m *GraphQL) XXX_Size() int {
	return xxx_messageInfo_GraphQL.Size(m)
}
func (m *GraphQL) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQL.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQL proto.InternalMessageInfo

func (m *GraphQL) GetFields() []*GraphQLField {
	if m != nil {
		return m.Fields
	}
	return nil
}

// Holds information a GraphQL request
type CheckRequest struct {
	Source               *Source  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Http                 *Http    `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	Graphql              *GraphQL `protobuf:"bytes,3,opt,name=graphql,proto3" json:"graphql,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *CheckRequest) GetHttp() *Http {
	if m != nil {
		return m.Http
	}
	return nil
}

func (m *CheckRequest) GetGraphql() *GraphQL {
	if m != nil {
		return m.Graphql
	}
	return nil
}

type GraphQLFieldResponse struct {
	// path to the graphql field from starting with the operation type.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// an execution error associated with the given field.
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphQLFieldResponse) Reset()         { *m = GraphQLFieldResponse{} }
func (m *GraphQLFieldResponse) String() string { return proto.CompactTextString(m) }
func (*GraphQLFieldResponse) ProtoMessage()    {}
func (*GraphQLFieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *GraphQLFieldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQLFieldResponse.Unmarshal(m, b)
}
func (m *GraphQLFieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQLFieldResponse.Marshal(b, m, deterministic)
}
func (m *GraphQLFieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQLFieldResponse.Merge(m, src)
}
func (m *GraphQLFieldResponse) XXX_Size() int {
	return xxx_messageInfo_GraphQLFieldResponse.Size(m)
}
func (m *GraphQLFieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQLFieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQLFieldResponse proto.InternalMessageInfo

func (m *GraphQLFieldResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GraphQLFieldResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CheckResponse struct {
	Fields []*GraphQLFieldResponse `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// validation errors to report back to the client.  If any are set, the entire graphql request fails.
	ValidationError      []string `protobuf:"bytes,2,rep,name=validationError,proto3" json:"validationError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetFields() []*GraphQLFieldResponse {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *CheckResponse) GetValidationError() []string {
	if m != nil {
		return m.ValidationError
	}
	return nil
}

func init() {
	proto.RegisterType((*Source)(nil), "proto.Source")
	proto.RegisterType((*Header)(nil), "proto.Header")
	proto.RegisterType((*Http)(nil), "proto.Http")
	proto.RegisterType((*GraphQLField)(nil), "proto.GraphQLField")
	proto.RegisterType((*GraphQL)(nil), "proto.GraphQL")
	proto.RegisterType((*CheckRequest)(nil), "proto.CheckRequest")
	proto.RegisterType((*GraphQLFieldResponse)(nil), "proto.GraphQLFieldResponse")
	proto.RegisterType((*CheckResponse)(nil), "proto.CheckResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x25, 0xb4, 0x49, 0xe9, 0x64, 0x0b, 0x92, 0xa9, 0x50, 0xb4, 0x20, 0x58, 0x59, 0x42, 0x44,
	0x42, 0xda, 0x43, 0x16, 0x71, 0x06, 0xad, 0x80, 0x3d, 0x70, 0x00, 0xc3, 0x0f, 0x98, 0x64, 0x68,
	0x22, 0xb2, 0xb1, 0xd7, 0x76, 0x2b, 0xed, 0x8d, 0x3b, 0x3f, 0x8d, 0x3c, 0xb1, 0xb7, 0xe9, 0xaa,
	0xa7, 0xce, 0xbc, 0x79, 0xd3, 0xf7, 0xe6, 0x39, 0xb0, 0xb2, 0x68, 0x76, 0x5d, 0x8d, 0xe7, 0xda,
	0x28, 0xa7, 0x58, 0x4a, 0x3f, 0x9c, 0x43, 0xf6, 0x43, 0x6d, 0x4d, 0x8d, 0xac, 0x80, 0x85, 0x6c,
	0x1a, 0x83, 0xd6, 0x16, 0xc9, 0x59, 0x52, 0x2e, 0x45, 0x6c, 0x79, 0x05, 0xd9, 0x15, 0xca, 0x06,
	0x0d, 0x63, 0x30, 0x1f, 0xe4, 0x35, 0x06, 0x02, 0xd5, 0x6c, 0x0d, 0xe9, 0x4e, 0xf6, 0x5b, 0x2c,
	0x1e, 0x12, 0x38, 0x36, 0xfc, 0x5f, 0x02, 0xf3, 0x2b, 0xe7, 0xb4, 0x5f, 0x69, 0x95, 0x75, 0x71,
	0xc5, 0xd7, 0xec, 0x19, 0x64, 0xd7, 0xe8, 0x5a, 0xd5, 0x84, 0x9d, 0xd0, 0x79, 0xae, 0x96, 0xae,
	0x2d, 0x66, 0x23, 0xd7, 0xd7, 0xec, 0x14, 0x1e, 0x91, 0xd3, 0x5a, 0xf5, 0xc5, 0x9c, 0xf0, 0xbb,
	0x9e, 0xbd, 0x81, 0x45, 0x4b, 0xc6, 0x6c, 0x91, 0x9e, 0xcd, 0xca, 0xbc, 0x5a, 0x8d, 0xc7, 0x9d,
	0x8f, 0x76, 0x45, 0x9c, 0x72, 0x07, 0x27, 0x5f, 0x8c, 0xd4, 0xed, 0xf7, 0xaf, 0x9f, 0x3b, 0xec,
	0xf7, 0x42, 0xc9, 0x44, 0xe8, 0x25, 0x80, 0x96, 0x06, 0x07, 0xf7, 0xf3, 0x56, 0xc7, 0x63, 0x26,
	0x08, 0x7b, 0x01, 0xcb, 0xdf, 0x7e, 0x99, 0xc6, 0xa3, 0xc3, 0x3d, 0xe0, 0xff, 0x51, 0x9a, 0x8d,
	0x0d, 0x16, 0xa9, 0xe6, 0xef, 0x61, 0x11, 0x54, 0xd9, 0x5b, 0xc8, 0x88, 0xeb, 0xb3, 0xf5, 0x46,
	0x9f, 0x06, 0xa3, 0x53, 0x57, 0x22, 0x50, 0xf8, 0xdf, 0x04, 0x4e, 0x2e, 0x5b, 0xac, 0xff, 0x08,
	0xbc, 0xd9, 0xa2, 0x75, 0xec, 0x35, 0x64, 0x96, 0x1e, 0x89, 0x0c, 0xef, 0xcf, 0x1c, 0x5f, 0x4e,
	0x84, 0x21, 0x7b, 0x05, 0xf3, 0xd6, 0x39, 0x4d, 0xde, 0xf3, 0x2a, 0x8f, 0x59, 0x38, 0xa7, 0x05,
	0x0d, 0x58, 0x09, 0x8b, 0x8d, 0x17, 0xbc, 0xe9, 0xe9, 0x80, 0xbc, 0x7a, 0x7c, 0x68, 0x43, 0xc4,
	0x31, 0xff, 0x00, 0xeb, 0x03, 0x6b, 0x68, 0xb5, 0x1a, 0x2c, 0x1e, 0x0d, 0x6e, 0x0d, 0x29, 0x1a,
	0xa3, 0x4c, 0xfc, 0x00, 0xa8, 0xe1, 0x03, 0xac, 0xc2, 0x0d, 0x61, 0xf5, 0xe2, 0x5e, 0x04, 0xcf,
	0x8f, 0x45, 0x10, 0xc8, 0x31, 0x0a, 0x56, 0xc2, 0x93, 0x9d, 0xec, 0xbb, 0x46, 0xba, 0x4e, 0x0d,
	0x9f, 0x82, 0xca, 0xac, 0x5c, 0x8a, 0xfb, 0x70, 0x75, 0x09, 0xf9, 0x37, 0xd5, 0x77, 0xf5, 0xed,
	0xc7, 0x0d, 0x0e, 0x8e, 0xbd, 0x83, 0x94, 0xe4, 0x59, 0x4c, 0x7a, 0x1a, 0xe8, 0xe9, 0xfa, 0x10,
	0x1c, 0x45, 0xf9, 0x83, 0x5f, 0x19, 0xc1, 0x17, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x2f,
	0x4d, 0xfc, 0x2c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PolicyAgentClient is the client API for PolicyAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PolicyAgentClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type policyAgentClient struct {
	cc *grpc.ClientConn
}

func NewPolicyAgentClient(cc *grpc.ClientConn) PolicyAgentClient {
	return &policyAgentClient{cc}
}

func (c *policyAgentClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/proto.PolicyAgent/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyAgentServer is the server API for PolicyAgent service.
type PolicyAgentServer interface {
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
}

func RegisterPolicyAgentServer(s *grpc.Server, srv PolicyAgentServer) {
	s.RegisterService(&_PolicyAgent_serviceDesc, srv)
}

func _PolicyAgent_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyAgentServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PolicyAgent/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyAgentServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PolicyAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PolicyAgent",
	HandlerType: (*PolicyAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _PolicyAgent_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
